version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Shanghai
    versioning-strategy: lockfile-only
    open-pull-requests-limit: 2
    commit-message:
      prefix: 构建(依赖)
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 2
    commit-message:
      prefix: 构建(依赖)
    groups:
      github-actions:
        patterns:
          - "*"
